CREATE TABLE person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL,
    age int CHECK ( age > 0 ) NOT NULL,
    email varchar NOT NULL
);

CREATE TABLE item(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int REFERENCES person(id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);